import * as types from "../types";
import _ from "lodash";
import history from "../../history";

export const fetchGalleryItems = () => async (dispatch) => {
  //   const response = await api.get("/users/profile");
  const response = getGalleries;
  dispatch({ type: types.FETCH_GALLERIES, payload: response.data });
};

const getGalleries = {
  data: [
    {
      id: 1,
      title: "USA Geothermal",
      time: "11/27/2020",
      url: "http://mail.com",
      username: "mail project",
      collaborationGroup: "Lab Internal",
      description: "this is a mail project",
      source: "Untitled10.png",
    },
    {
      id: 2,
      title: "Well Optimization",
      time: "10/21/2020",
      url: "http://web.com",
      username: "web project",
      collaborationGroup: "Lab Internal",
      description: "this is a web project",
      source: "Untitled5.png",
    },
    {
      id: 3,
      title: "Well Optimization",
      time: "12/01/2020",
      url: "http://example.com",
      username: "example project",
      collaborationGroup: "Lab Internal",
      description: "this is a example project",
      source: "Untitled3.png",
    },
    {
      id: 4,
      title: "Well Optimization",
      time: "12/01/2020",
      url: "http://example.com",
      username: "example project",
      collaborationGroup: "Lab Internal",
      description: "this is a example project",
      source: "Untitled7.png",
    },
    {
      id: 5,
      title: "USA Geothermal",
      time: "12/18/2020",
      url: "http://archive.com",
      username: "archive project",
      collaborationGroup: "Lab Internal",
      description: "this is a archive project",
      source: "Untitled4.png",
    },
    {
      id: 6,
      title: "Well Optimization",
      time: "10/21/2020",
      url: "http://web.com",
      username: "web project",
      collaborationGroup: "Lab Internal",
      description: "this is a web project",
      source: "Untitled1.png",
    },
    {
      id: 7,
      title: "USA Geothermal",
      time: "11/27/2020",
      url: "http://mail.com",
      username: "mail project",
      collaborationGroup: "Lab Internal",
      description: "this is a mail project",
      source: "Untitled6.png",
    },
    {
      id: 8,
      title: "USA Geothermal",
      time: "11/27/2020",
      url: "http://mail.com",
      username: "mail project",
      collaborationGroup: "Lab Internal",
      description: "this is a mail project",
      source: "Untitled2.png",
    },
    {
      id: 9,
      title: "USA Geothermal",
      time: "12/18/2020",
      url: "http://archive.com",
      username: "archive project",
      collaborationGroup: "Lab Internal",
      description: "this is a archive project",
      source: "Untitled8.png",
    },
    {
      id: 10,
      title: "Well Optimization",
      time: "10/21/2020",
      url: "http://web.com",
      username: "web project",
      collaborationGroup: "Lab Internal",
      description: "this is a web project",
      source: "Untitled9.png",
    },
    {
      id: 11,
      title: "2D Flow Contour",
      time: "09/09/2020",
      url: "http://test.com",
      username: "test project",
      collaborationGroup: "Lab Internal",
      description: "EAI Geo Model",
      source: "Untitled.png",
    },
    {
      id: 12,
      title: "Well Optimization",
      time: "12/01/2020",
      url: "http://example.com",
      username: "example project",
      collaborationGroup: "Lab Internal",
      description: "this is a example project",
      source: "Untitled11.png",
    },
    //   {
    //     id: 13,
    //     title: "USA Geothermal",
    //     time: "12/18/2020",
    //     url: "http://archive.com",
    //     username: "archive project",
    //     collaborationGroup: "Lab Internal",
    //     description: "this is a archive project",
    //     source: null,
    //   },
  ],
};
